releases:
  - name: rediscart
    chart: charts/redis
    values: 
      - values/redis-values.yaml
      - appReplicas: "1"
      - volumeName: "redis-cart-data"
  
  - name: emailservice
    chart: charts/microservice
    values:
      - values/email-service-values.yaml

  - name: cartservice
    chart: charts/microservice
    values:
      - values/cartservice-service-values.yaml    

  - name: currencyservice
    chart: charts/microservice
    values:
      - values/currencyservice-service-values.yaml   

  - name: paymentservice
    chart: charts/microservice
    values:
      - values/paymentservice-service-values.yaml

  - name: recommendationservice
    chart: charts/microservice
    values:
      - values/recommendation-service-values.yaml

  - name: productcatalogservice
    chart: charts/microservice
    values:
      - values/productcatalog-service-values.yaml

  - name: shippingservice
    chart: charts/microservice
    values:
      - values/shippingservice-service-values.yaml

  - name: adservice
    chart: charts/microservice
    values:
      - values/adservice-service-values.yaml

  - name: checkoutservice
    chart: charts/microservice
    values:
      - values/checkoutservice-service-values.yaml

  - name: frontendservice
    chart: charts/microservice
    values:
      - values/frontend-service-values.yaml