
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EZ3dNekU1TVRJeU5Wb1hEVE16TURjek1URTVNVEl5TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHVKCkQ0eUgrM1ZTR2Fodm9Fbk5UazI2Y2hXUlRxMVJtSTd2cW14REFPaVNKbXUvUFMrbzB4ZDlsdkNONTc1MEJWbkgKTi9jYTNWcGpHd1Q5dHVycTEyUnErRTczby9VSm5lUkZuQ1YvVks0V0RNeDBGUkhqcC9JcElhdk5LQzFEM0k0KwphbWFpeE1rblNzTW1lcVpvSzNlNGdzZFRWdGVzQjdlVENXSTV4SWZHdjlrbDRWNVd1UFNCbVVhWVFnVmdkL1kyCnhHU2ZZSGxTclNMVlJnbVcwRFY4bFBWUnJ0N0w4dkIvVldYamVHT01MQW9OaG1nRlh3S1l2Y3pEajRTdG5kUlkKRjJQWkdPZnUxMnZGWFJyajlXWm5ONHFQZU5GUkN3QVV0VDU5M0FIWWJuTjV2TlJZZnlNNzZNYmpXdEM1QUFvMwpwd1dwWU0vekFDamUwS1MzZnlzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGZld6M3k3VkFzejU0SWpSTDZML2gyU2VVTGlNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS1NDdFcycHAzQStyWWVOaCtnUQpLdUdOR1ZCOWlhTWVmN2tXcEVYQnZmYmx0dmN1eUlodnNFblU1S25NeW82anpTRGpkYzVKVk9yemNoVGlzdjAwCjJlS1N5QXFDT0NuWnp6UmZnS09XVGxvcFhhK3hMSXhrNG02S0FYVVphUXNJVHRTamhkd2UwRFg2VmZpa1VoY0IKeHNyemlraFZFL2E3OGJRNWpmRTNyRDZsQzgyelptd0FydHBNWGo1S0Ezd0VCdHh3Ry8yKzFUZnBQTmQzVTl3YgpxaFVGOFduTXREcEV2cUNibERzZ1J3TnQ2QzlRTkR4R0NSOEZRZTdKZmxJZzh6cSsvSHJ5aXcvMHpDdDA3Vkg3CmlPMjNqYWVLVmlyM0hSd1ZKNG9TVjRmU1NacDhiSTNxTTZ3NGUzeVRRQmdyeFNBZ0VUQXBVVzd2YTZYWmNmY2gKeHg4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://8a71366c-60f0-42c6-a095-339895cd7369.eu-central-1.linodelke.net:443
  name: lke122526

users:
- name: lke122526-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Inl2SUgzX0l4UERES1o4RGhBNU9ZeHhiQlpqT1o0T0JhakNDRkVIaU9vTVkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tdGNoZ24iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTc1Y2YzZjktMTEwZS00ZWYzLTgxMDEtOTE0ZjlkZDgzNTRiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.1XYI0fYhlKLr6bjKm7O-d5lmoGQV-fXvuNvas-PAeXSEI2rP6smlRSz-UIzMWpcvWXMYLezLVb-eX7su-SSxxBXHPc0gjMoX9yqe0ldEnvV86rL8XmUqd44-LInqW9oKoHKlMvt0i0EGx9qjyUiWML04PBw3rsm_6R4oLq-gl4Ck_7XRj4BUDkLPZ_dCNTrFOx0gylw8wiUR7iOnOaGN090NxCArCdaAHjc_g2kYUs9Bgs0nMNgRxtT8QmOlBK6E4-q-DKHEvrOIdjcyL_EAmqRrUEIUvxm_XGlAfb9uhN81fZtrpqk7XhPYHCK_asImbOFMyqLTgYBfepiF99Y-DA

contexts:
- context:
    cluster: lke122526
    namespace: default
    user: lke122526-admin
  name: lke122526-ctx

current-context: lke122526-ctx
