apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
