#done
appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 7000
containerEnvVars:
- key: PORT
  value: 7000
- key: DISABLE_TRACING
  value: "1"
- key: DISABLE_PROFILER
  value: "1"

servicePort: 7000