#done
appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 8080
containerEnvVars:
- key: PORT
  value: 8080
- key: DISABLE_TRACING
  value: "1"
- key: DISABLE_PROFILER
  value: "1"

servicePort: 5000