#done
appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 50051
containerEnvVars:
- key: PORT
  value: 50051
- key: DISABLE_TRACING
  value: "1"
- key: DISABLE_PROFILER
  value: "1"

servicePort: 50051