apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.echoServer.name }}-service
spec:
  type: {{ .Values.echoServer.service.type }}
  selector:
    app: {{ .Values.echoServer.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.echoServer.service.port }}
      targetPort: {{ .Values.echoServer.service.port }}helm install nginx-ingress ingress-nginx/ingress-nginx