
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EZ3hPREV6TVRrME5sb1hEVE16TURneE5URXpNVGswTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHIxCk9UcHluaHpOVytyeFNFL0R4TUdZV1hoOVhZQ3ZqaDgxMUVhUE9yeVRNVUpiTXh6azdtQ2xQQ0E4WWFUYVZSNVAKNHBjRjZpL3k0VUtTMy9zeW0yRkIzSGViZHpYV3M1d3ZyMDJnd2IxencvL3F3R3AxdEdJb04zZCtXcURNVVlodApIdUhqenNjaVUwRmhlVlphVlk2SFc0eHhXZTJ5dEc4ZlZoUE85blhWYVkvMERLMjZ4R20wakJRKzRVYjFEcDQyCkJLQ2t6K09FWDZvR1I3WDZwZWVVL3BIdnozSUxvS1VoUUF5OC9TcG1qazFHM3hPY01wNDRIYUFPbXZIeEZDRGYKbWViOXA0bHJBMVY2THRuMGVISmNVV2I0VzFRbDJLRHRBZnNMbGhMUFcvc3V6OUEzNkpmOG0xRFhWTWVHQjVZeApGdmNaYU1DNFo3RXdnZFJ0dHhzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEQzdwMnoxak9uUjdYSlNOSXp1RFJkb0JGRS9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRklDYUxoRkZLSTZMTllzYjBQVgoyWXlTQmZ2WXZIcE5lYjE2SXZSdGwzMXdyZkQyRXhrSVIweXUwWFZEWnlvSVpmV2t4S3hPTElKbXlobVVnTHdqClZrQmJXUHFUZVNTWFZvbVRGWEFDNjBWSVNSbndGcThJeHorZFptc1Vsc0ZvMDVyVzFjblc3cHZ4YlhjYjlyOTYKSXlSMnRudGJ4K3BEV2ltdnp2WHBnc2dzUVBrMUtiODNBcUVweHBZNmI3WWE2ZXF0SmIyZ0QvM0MvNkZOdWdPUgpmMHRQYlVLamZ6NWs4RWJCRmtiMDRiQXVDdjhsZ0xhZzE5VU50d3d0NXhQa0tTeFJ3OWVlNlhQYWM2aEZiRWJECkdad21QK1RPMUxRSG9RU0ErdlpIZEFzcEhwYS8yNGpDeDFtQnVvSytqQlBzVFJUV3l3U1lUZmhsaWxXWTZiMkMKM3o4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://7f9e0267-6124-4b1b-a50a-2de4aeb77bda.eu-central-2.linodelke.net:443
  name: lke125618

users:
- name: lke125618-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjFibWFBV0FDM1JUWjdfVG5Mcm16MHVVd3ZicjdJVFp6OVVLdGlRQnBiTWcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNThic3AiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDliOWM4NGMtZWZkMS00NjRmLWIzY2YtYjI1M2UyMzYwYWFmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.LQbMyWdc_uO-_wBhm7mKv7jCkVtOFaGGmM0BCcK-Xulc824Sc9e5Cfq8Ymdc2Oda94GzWdtOgOXbt1TCYBU1mVU6WygcOpVYeZrJCRsz6E1D3UtTvjlHb1VWE0c3CW4-tw6z6sTudwE41gMU_p2f-4dz65K7_GgLIoxB3NF46e6Dt1GMy7vH_49mTRZ-2ZWOe5TqCXjAo0T5GBxWHrShdDZ-4FptNDGifdQ34iXYdOyXcn7qttnd39coGLf_g7Mnt9zSEJv-HDGzGZKoGO9HLAj-1SRLqV7FBqgXVHsdN-bQGJOzKixVm_nsTnLggu2OED_ClSej-KWFobY8-cGy0w

contexts:
- context:
    cluster: lke125618
    namespace: default
    user: lke125618-admin
  name: lke125618-ctx

current-context: lke125618-ctx
